hasura:
  service:
    nodePort: 30339
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

tezos-marketplace-indexer-rarible:
  enabled: false
  replicas: 0
  environments:
    TZKT_URL: https://api.ghostnet.tzkt.io
    HASURA_URL: http://hasura:8080
    NETWORK: ghostnet

tezos-marketplace-indexer-tezos:
  enabled: false
  replicas: 0
  environments:
    TZKT_URL: https://api.ghostnet.tzkt.io
    HASURA_URL: http://hasura:8080
    NETWORK: ghostnet

tezos-marketplace-indexer-metadata:
  environments:
    TZKT_URL: https://api.ghostnet.tzkt.io
    HASURA_URL: http://hasura:8080
    NETWORK: ghostnet
  resources:
    limits:
      memory: 768Mi
    requests:
      memory: 512Mi

aux-hasura:
  enabled: false
  replicas: 0

aux-tezos-marketplace-indexer-rarible:
  enabled: false
  replicas: 0

tzkt:
  enabled: false
  api:
    image:
      repository: fpto/rarible-tzkt-api
      tag: 1.10.0
    resources:
      limits:
        memory: 768Mi
      requests:
        memory: 512Mi
  indexer:
    image:
      repository: fpto/rarible-tzkt-indexer
      tag: 1.10.0
  network: ghostnet
  service:
    nodePort: 30340
  environments:
    TezosNode__Endpoint: https://rpc.tzkt.io/ghostnet
    TokenMetadata__DipDup__Url: https://metadata.dipdup.net/v1/graphql
  ingress:
    hostname: 'tezos-tzkt.dev.rarible.int'
    path: /
    ingressClassName: ingress-internal
    backend:
      service: tzkt
      port: http
