hasura:
  replicas: 1
  service:
    nodePort: 30139
  resources:
    limits:
      cpu: '1'
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

tezos-marketplace-indexer-rarible:
  image:
    tag: master-3a1f7c-231
  command: [
    "dipdup", "-c", "dipdup.yml",
    "-c", 'dipdup.{{ include "app.env" $ }}.rarible.yml',
    "run"
    ]
  replicas: 1
  environments: 
    TZKT_URL: http://tzkt:5000
    NETWORK: mainnet

tezos-marketplace-indexer-tezos:
  image:
    tag: master-3a1f7c-231
  command: [
    "dipdup", "-c", "dipdup.yml",
    "-c", 'dipdup.{{ include "app.env" $ }}.tezos.yml',
    "run"
  ]
  replicas: 1
  environments:
    TZKT_URL: http://tzkt:5000
    NETWORK: mainnet

tezos-marketplace-indexer-metadata:
  enabled: false
  replicas: 0
  environments:
    TZKT_URL: http://tzkt:5000
    NETWORK: mainnet

aux-hasura:
  replicas: 1
  resources:
    limits:
      cpu: '1'
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

aux-tezos-marketplace-indexer-rarible:
  enabled: true
  replicas: 1
  image:
    repository: tezos-marketplace-indexer
  environments:
    TZKT_URL: http://tzkt:5000
    NETWORK: mainnet

tzkt:
  enabled: true
  api:
    resources:
      limits:
        cpu: '1'
        memory: 3Gi
      requests:
        cpu: 200m
        memory: 1384Mi
    image:
      repository: fpto/rarible-tzkt-api
      tag: 1.10.0
  indexer:
    image:
      repository: fpto/rarible-tzkt-indexer
      tag: 1.10.0
    resources:
      limits:
        cpu: 400m
        memory: 2Gi
      requests:
        cpu: 200m
        memory: 384Mi
  network: mainnet
  service:
    nodePort: 30140
  environments:
    TezosNode__Endpoint: https://rpc.tzkt.io/mainnet
    TokenMetadata__DipDup__Url: https://metadata.dipdup.net/v1/graphql
  ingress:
    hostname: 'tezos-tzkt.rarible.int'
    path: /
    ingressClassName: ingress-internal
    backend:
      service: tzkt
      port: http