hasura:
  replicas: 0
  service:
    nodePort: 30139

tezos-marketplace-indexer:
  replicas: 0
  environments: 
    TZKT_URL: http://tzkt:5000
    NETWORK: mainnet
    UNION_API: https://api.rarible.org
    LEGACY_API: https://tezos-api.rarible.org

tzkt:
  enabled: true
  service:
    nodePort: 30140
  environments:
    TezosNode__Endpoint: https://rpc.tzkt.io/mainnet
    TokenMetadata__DipDup__Url: https://metadata.dipdup.net/v1/graphql