hasura:
  service:
    nodePort: 30439

tezos-marketplace-indexer-rarible:
  replicas: 1
  environments:
    TZKT_URL: https://api.ghostnet.tzkt.io
    NETWORK: ghostnet

tezos-marketplace-indexer-tezos:
  replicas: 1
  environments:
    TZKT_URL: https://api.ghostnet.tzkt.io
    NETWORK: ghostnet

tezos-marketplace-indexer-metadata:
  replicas: 1
  environments:
    TZKT_URL: https://api.ghostnet.tzkt.io
    NETWORK: ghostnet

tzkt:
  enabled: false
  api:
    resources:
      limits:
        memory: 768Mi
      requests:
        memory: 512Mi
    image:
      repository: fpto/rarible-tzkt-api
      tag: v0.3.0
  indexer:
    image:
      repository: fpto/rarible-tzkt-indexer
      tag: v0.3.0
  network: ghostnet
  service:
    nodePort: 30440
  environments:
    TezosNode__Endpoint: https://rpc.tzkt.io/ghostnet
    TokenMetadata__DipDup__Url: https://metadata.dipdup.net/v1/graphql
  ingress:
    hostname: 'tezos-tzkt.testnet.rarible.int'
    path: /
    ingressClassName: ingress-internal
    backend:
      service: tzkt
      port: http