hasura:
  service:
    nodePort: 30439

tezos-marketplace-indexer:
  replicas: 1
  environments: 
    TZKT_URL: http://tzkt:5000
    NETWORK: ithacanet
    UNION_API: https://testnet-api.rarible.org
    LEGACY_API: https://test-tezos-api.rarible.org

tzkt:
  enabled: true
  service:
    nodePort: 30440
  environments:
    TezosNode__Endpoint: https://rpc.tzkt.io/ithacanet