tezos-marketplace-indexer:
  image:
    repository: tezos-marketplace-indexer
  command: [ 
    "dipdup", "-c", "dipdup.yml",
    "-c", 'dipdup.{{ include "service.env" $ }}.yml',
    "run"
    ]
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.env" $ }}'
    # provided via secrets
    # POSTGRES_HOST:
    # POSTGRES_DB:
    # POSTGRES_USER:
    # POSTGRES_PASS:
    # KAFKA_ADDRESS:
    # KAFKA_SASL_MECHANISM:
    # KAFKA_USERNAME:
    # KAFKA_PASSWORD:
    # HASURA_GRAPHQL_ADMIN_SECRET:

  livenessProbe: false
  readinessProbe: false
  # resources:
  #   requests:
  #     memory: 128M
  #   limits:
  #     memory: 256M
  
hasura:
  image: 
    registry: docker.io
    repository: hasura/graphql-engine
    tag: v2.2.0
  service:
    enabled: true
  environments:
    HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
    HASURA_GRAPHQL_DEV_MODE: "true"
    HASURA_GRAPHQL_ENABLED_LOG_TYPES: "startup, http-log, webhook-log, websocket-log, query-log"
    HASURA_GRAPHQL_UNAUTHORIZED_ROLE: user
    HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES: "true"
    # provided via secrets
    # HASURA_GRAPHQL_ADMIN_SECRET:
    # HASURA_GRAPHQL_DATABASE_URL:
 